### ISSUE TITLE
How does Steam API work?

### ISSUE THREAD

**Issue by Whoeza** [drwahl/Dota2-replay-downloader#1]
Hi! I was wondering: is the API key linked to your Steam account? If so, does it mean you can download only the matches for your account? Or can you use this to download any available replay from an user's history?
Cheers!
o/

**Comment by drwahl** [comment]
Yes, the API key is linked to your account. It's been a long time since I touched this code, so I don't recall the specifics exactly, but I'm pretty sure you can only download your replays, not other peoples replays.
